faq.md

Tracked in https://gitlab.eclipse.org/eclipse-wg/open-regulatory-compliance-wg/cra-faq/-/issues/4
Originally raised in https://www.eclipse.org/lists/open-regulatory-compliance/msg00220.html

Add FAQ on criteria to determine CRA scope

---

faq.md

This is part of a [question that was raised on the ORC WG mailing list](https://www.eclipse.org/lists/open-regulatory-compliance/msg00423.html) about the definition of legal persons in Europe. I've broken down the question into four parts:
- What is an _open-source software steward_? (already answered [here](https://github.com/orcwg/cra-hub/blob/main/faq.md#q-what-is-an-open-source-software-steward))
- What is a _legal person_?
- Can an solo maintainer be considered to be an _open-source software steward_?
- Can a loosely organized group of maintainers be considered to be an _open-source software steward_?
Currently, this pull request only addressed the last question.

Add FAQ about whether maintainers are open source stewards

---

faq.md

Leveraging mermaid diagrams to visualize some of the key aspects of the CRA seems very valuable.
I'm not sure whether this belongs in the FAQ or as a separate document. Thoughts welcomed.
This is what the rendered version looks like:

Add CRA implementation timeline to FAQ

---

faq.md

Proposes and addresses two FAQ about the CRA: what's in scope of the CRA ans what isn't.

Add FAQs on CRA scope

---

faq.md

Add FAQs about stewards obligations

---

faq.md

Add introductory paragraph to FAQ

---

inventory.md

I've added a few OWASP resources. More are to come but I'd like to use this pull request to discuss where various resources should go.

Adding a first set of OWASP resources for review

---

inventory.md

It also contains link to the document for security classification.
I should note that we (PHP security team) are currently discussing some changes in the classification. The policies should be also extended to describe our processes hopefully soon.

Extend inventory with PHP security resources

---

faq.md

Add maturity level definition

---

inventory.md

Link spreadsheet from inventory.md

---

inventory.md

SSDF stands for Secure Software Development Framework, as issued by the Computer Security Resource Center (CSRC) of NIST, US Department of Commerce.

inventory: link to the SSDF

---

inventory.md

Add EUCC Scheme Guidelines on Vulnerability Management and Disclosure from ENISA.

inventory.md: add EUCC schema

---

README.md

Makes it easier to include links elsewhere

Separate links in README

---

faq.md

Addresses point (1) in https://github.com/orcwg/cra-hub/pull/138#issuecomment-2703699890

Add caution note to FAQ tmp-1

---

inventory.md

Adding in FIRST PSIRT and CSIRT services frameworks

adding PSIRT/CSIRT details to inventory

---

faq.md

- Clarify that reporting obligations starting date affects manufacturers and stewards alike.
- Properly source starting times for the different implementation phases.

Fix error in FAQ diagram

---

faq.md

spelling fix

---

faq.md

- I wasn't sure if or how I should add all the references
- I wasn't sure if I should add a second question instead: One explaining what a harmonised standard is, another one explaining what a referenced standard is + presumption of conformity
This is switching to the relatively common format of one sentence per line which makes diffs easier in the future.
My IDE also complains that the "name" attribute is deprecated and should be replaced by "id". Happy to include that here if you like.

Clarify difference between harmonised and referenced standard

---

faq.md

Fixes a mistake from @tieguy in https://github.com/orcwg/cra-hub/pull/188#issuecomment-2797321040

Fix duplication

---

faq.md

Several new Qs and As, breaking up answers in response to #133
Note that not all the deep links work because I want to get comment on the style first, will fix those later.

Add new questions about maintainers and obligations

---

faq.md

Approves the answers to the following questions:
What is the CRA? #154
Where is the official text of the CRA? #155
When will the CRA start applying? #10 
What is in scope of the CRA? #2

Approve answers to questions on the CRA itself

---

inventory.md

Add Telco WG SBOM guide to inventory

---

faq.md

FAQ entry 30 lacks justification.
While it's nice to have an answer, it's important
to *justify* that answer with citations.
This adds justifications and quotes to help give people confidence that this is the *correct* answer.

Add justifications for FAQ entry 30

---

faq.md

fixed stewards plural here and there

Fixed typos

---

faq.md

This is based on @Viko-legal's answer in #34, however made more general to cover all use cases. I also tried to make it more clear who is allowed to affix the mark and who isn't.

Add answer to #34 concerning who needs to affix the CE mark
